"use client";
import Sidebar from "@/components/Sidebar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useState } from "react";
import { Providers } from "@/redux/Providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Instagram _clone",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   const [tabActive, setTabActive] = useState<string>("");
   return (
      <html lang="en" data-theme={"light"}>
         <body className={`flex flex-row ${inter.className} scrollbar-hide`}>
            <Providers>
               <Sidebar tabActive={tabActive} onClickTab={setTabActive} />
               <main className="w-full flex min-h-screen flex-col items-center justify-between mx-[131px]">
                  {children}
               </main>
            </Providers>
         </body>
      </html>
   );
}
